### ISSUE TITLE
没有api，实际的流程就少了很多！

### ISSUE THREAD

**Issue by luuman** [RebeccaHanjw/weapp-wechat-zhihu#2]
关注，标题只显示两行，内容显示三行，有推荐话题，上滑隐藏搜索框！

**Comment by RebeccaHanjw** [comment]
确实, 不过知乎不开放 api 我也是很心塞, 还有就是如果很多细节功能都放上去的话, 其实实际编译出来的包很容易会超过1M 吧

**Comment by luuman** [comment]
知乎不太适合小程序，其实只做部分功能也不错。比如：live

**Comment by RebeccaHanjw** [comment]
嗯嗯, 以后再做 demo 我一定要先评估下仿的原版的情况, 尤其 api....::>_<::

**Comment by luuman** [comment]
哈哈，我准备做个微信小程序-淘票票，然而也没有api，现在网上只有豆瓣开放接口了

**Comment by RebeccaHanjw** [comment]
知乎之前有前辈写了爬虫放到服务器做了开放的非官方 api, 但是前一段时间关闭了, 淘票票的话, 就算有开放 api, 真上线到微信的平台上, 阿里的域名会不会被......

**Comment by luuman** [comment]
淘票票没有api，阿里被强了，我用的是猫眼的哈哈，就是个demo而已。

**Comment by luuman** [comment]
妹子会Python呀？

**Comment by luuman** [comment]
猫眼的api真烂

**Comment by RebeccaHanjw** [comment]
啊...我的 Python 就是会点基本的而已, 没尝试过用 Python 做开发, 跟不会也差不多, 学 Python 比较早, 是图大学的时候做作业啊, 跑数据啊啥的方便

**Comment by luuman** [comment]
今天知乎9:00有大神live

**Comment by RebeccaHanjw** [comment]
我才看到信息....错过了😔

**Comment by luuman** [comment]
微信号多少！

**Comment by luuman** [comment]
微信号多少！
